#!/bin/bash
set -eu -o pipefail

container=$1
database=$2
user=${3:-}
password_file=${4:-}

extra_file=''

if [[ -n $password_file ]]; then
	extra_file=$(
		docker exec --interactive "$container" sh -c '
			set -eu
			file=$(mktemp)
			printf "[client]\npassword=" > "$file"
			cat >> "$file"
		' < "$password_file"
	)
fi

param_file=$(
	docker exec --interactive "$container" sh -c '
		set -eu
		file=$(mktemp)
		cat > "$file"
		echo "$file"
	' <<< "$database"
)

result=$(
	docker exec --interactive "$container" mariadb --silent \
		${user:+--user="$user"} \
		${extra_file:+--defaults-extra-file="$extra_file"} \
	<<- EOF
		select schema_name
		from information_schema.schemata
		where schema_name = replace(load_file('$param_file'));
	EOF
)

docker exec "$container" rm "$param_file"

if [[ -n $extra_file ]]; then
	docker exec "$container" rm "$extra_file"
fi

[[ -n $result ]]
