#!/bin/bash
set -eu -o pipefail

container=$1
database=$2
user=${3:-}
password_file=${4:-}

extra_file=''

if [[ -n $password_file ]]; then
	extra_file=$(
		docker exec --interactive "$container" sh -c '
			set -eu
			file=$(mktemp)
			printf "[client]\npassword=" > "$file"
			cat >> "$file"
			echo "$file"
		' < "$password_file"
	)
fi

docker exec --interactive "$container" mariadb \
	${extra_file:+--defaults-extra-file="$extra_file"} \
	${user:+--user="$user"} \
	--database="$database"

if [[ -n $extra_file ]]; then
	docker exec "$container" rm "$extra_file"
fi
